[package]
name = "booktyping"
version = "0.1.0"
authors = ["Jesse Slater <jsssltr@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
dirs = "5.0.1"
ratatui = "0.24.0"
regex = "1.10.2"
